//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estate()
        {
            this.Agreements = new HashSet<Agreement>();
            this.Feedbacks = new HashSet<Feedback>();
            this.EstatePriceLogs = new HashSet<EstatePriceLog>();
        }
    
        public int ID { get; set; }
        public int OwnerID { get; set; }
        public string Address { get; set; }
        public int DistrictID { get; set; }
        public Nullable<int> RoomNumber { get; set; }
        public double TotalArea { get; set; }
        public Nullable<double> KitchenArea { get; set; }
        public Nullable<int> Floor { get; set; }
        public int FloorNumber { get; set; }
        public Nullable<int> EstateTypeID { get; set; }
        public Nullable<int> BuildingTypeID { get; set; }
        public Nullable<int> LoggiaNumber { get; set; }
        public Nullable<int> BalconyNumber { get; set; }
        public string PrivatePlot { get; set; }
        public string AdditionalBuildings { get; set; }
        public decimal Cost { get; set; }
        public System.DateTime Date { get; set; }
        public int BranchID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agreement> Agreements { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual BuildingType BuildingType { get; set; }
        public virtual District District { get; set; }
        public virtual EstateType EstateType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstatePriceLog> EstatePriceLogs { get; set; }
    }
}
