//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> EstateTypeID { get; set; }
        public Nullable<int> MultiFloorBuildingTypeID { get; set; }
        public Nullable<int> RoomNumber { get; set; }
        public Nullable<int> MinimalFloor { get; set; }
        public Nullable<int> MaximalFloor { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual District District { get; set; }
        public virtual EstateType EstateType { get; set; }
        public virtual MultiFloorBuildingType MultiFloorBuildingType { get; set; }
    }
}
